version: '3.8'

services:
  deepvisionxplain:
    image: ghcr.io/lus105/deepvisionxplain:latest
    
    ports:
      - "9090:8000"

    env_file:
      - .env
    
    volumes:
      # Mount config and data directories
      - ${host_config_dir}:/app/configs
      - ${host_data_dir}:/app/data
      - ${host_log_dir}:/app/logs
    
    environment:
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Europe/Vilnius
    
    # Fix for PyTorch DataLoader shared memory using host IPC
    ipc: host

    # Enable GPU support
    runtime: nvidia
    
    restart: unless-stopped

networks:
  deepvision_network:
    driver: bridge