# @package _global_

defaults:
  - override /data: dir
  - override /model: cnn_effnet_v2_s_down
  - override /trainer: gpu

tags: ["eval", "segmentation"]

data:
  data_dir: ${oc.env:pcb_data_path}
  save_predict_images: true

task_name: "predict"