# @package _global_

defaults:
  - override /data: dir
  - override /model: cnn
  - override /trainer: gpu

tags: ["test", "pcb", "mobilenet_v3_large"]

model:
  net:
    backbone: mobilenet_v3_large
    multi_head: false
    return_nodes: { "features.16": "layerout" }

data:
  data_dir: ${oc.env:pcb_data_path}

task_name: "eval"

ckpt_path: "models--DeepVisionXplain--mobilenet_v3_large_full_pcb"