# @package _global_

defaults:
  - override /data: dir
  - override /model: cnn_effnet_v2_s_down
  - override /trainer: gpu

tags: ["eval", "classification"]

model:
  net:
    multi_head: false

data:
  data_dir: ${oc.env:pcb_data_path}

task_name: "classification"