# @package _global_

defaults:
  - override /data: dir
  - override /model: cnn_effnet_v2_s_down
  - override /callbacks: default
  - override /trainer: default
  - override /logger: many_loggers

tags: ["train", "cnn"]

seed: 12345

trainer:
  min_epochs: 10
  max_epochs: 20
  gradient_clip_val: 0.5
  accelerator: gpu

model:
  net:
    multi_head: false
  ckpt_path: None

data:
  batch_size: 8
  num_workers: 4
  data_dir: ${oc.env:pcb_data_path}

logger:
  wandb:
    tags: ${tags}
    group: "pcb"
  aim:
    experiment: "efficientnet_v2_s_pcb_downscaled"