# @package _global_

# to execute this experiment run:
# python src/train.py runs=vit_train

defaults:
  - override /data: dir
  - override /model: vit
  - override /callbacks: default
  - override /trainer: default
  - override /logger: csv

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["vit", "VitRolloutMultihead"]

seed: 12345

trainer:
  min_epochs: 10
  max_epochs: 20
  gradient_clip_val: 0.5
  accelerator: gpu

model:
  optimizer:
    lr: 0.001
  compile: false

data:
  batch_size: 32
  data_dir: ${oc.env:pcb_data_path}
  preprocessor:
    tile_width: 224
    tile_height: 224
    min_defective_area: 0.1
    overlap: 10

logger:
  wandb:
    tags: ${tags}
    group: "vit"
  aim:
    experiment: "vit"