_target_: src.models.classification_module.ClassificationLitModule

net:
  _target_: ???

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

loss:
  _target_: torch.nn.BCELoss

compile: false

ckpt_path: ???
