defaults:
  - cnn
  - _self_

net:
  backbone: mobilenet_v3_large
  multi_head: true
  return_node: "features.13.block.0"

ckpt_path: ${paths.trained_models}/models--DeepVisionXplain--mobilenet_v3_large_down_pcb