defaults:
  - cnn
  - _self_

net:
  _target_: src.models.components.cnn_cam_multihead.CNNCAMMultihead
  backbone: torchvision.models/efficientnet_v2_s
  multi_head: False
  return_node: "features.7"
  weights: "IMAGENET1K_V1"