_target_: src.models.classification_module.ClassificationLitModule

net:
  _target_: src.models.components.vit_rollout_multihead.VitRolloutMultihead
  backbone: ???
  multi_head: False
  pretrained: True
  output_size: 1
  return_nodes: "attn_drop"
  head_name: "head"
  img_size: 224
  discard_ratio: 0.2
  head_fusion: "mean"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5e-5
  weight_decay: 0.0

scheduler: null

loss:
  _target_: torch.nn.BCELoss

compile: false

ckpt_path: ???